### ISSUE TITLE
Cannot find module 'pg'

### ISSUE THREAD

**Issue by mariushosting** [V-Shadbolt/docker-strapi#1]
Unable to install latest version
Igot the following error message in the logs:
Cannot find module 'pg'

**Comment by V-Shadbolt** [comment]
@mariushosting Apologies - missed the notification for this. 

Are you still seeing this issue with the latest v4 or v5 image? Are you upgrading an existing project or starting a new project?

**Comment by mariushosting** [comment]
> @mariushosting Apologies - missed the notification for this.
> 
> Are you still seeing this issue with the latest v4 or v5 image? Are you upgrading an existing project or starting a new project?

New Project from scratch new installation from scratch v5 image. 👍

**Comment by V-Shadbolt** [comment]
Can you share your logs and docker compose? I'm unable to reproduce the issue.

**Comment by mariushosting** [comment]
> Can you share your logs and docker compose? I'm unable to reproduce the issue.
https://pastebin.com/hVjc5d86

**Comment by mariushosting** [comment]
LOGS: https://pastebin.com/UHK9NJdN

**Comment by V-Shadbolt** [comment]
Thank you! This was helpful context. Took a look and it seems to be a known issue with Strapi x Postgres but is otherwise inconsistent. Are you using Windows by chance? Or are you on linux? 

Per the [Strapi blog](https://strapi.io/blog/postgre-sql-and-strapi-setup), If you get a “cannot find module ‘pg’” error, install it manually by running `yarn add pg` or `npm install --``save pg` within the project directory.

**Comment by mariushosting** [comment]
> Thank you! This was helpful context. Took a look and it seems to be a known issue with Strapi x Postgres but is otherwise inconsistent. Are you using Windows by chance? Or are you on linux?
> 
> Per the [Strapi blog](https://strapi.io/blog/postgre-sql-and-strapi-setup), If you get a “cannot find module ‘pg’” error, install it manually by running `yarn add pg` or `` npm install --``save pg `` within the project directory.

Linux, I will try those two solution and let you know.

**Comment by mariushosting** [comment]
Cannot find module 'mysql2' same issue but different module for mysql.

I give up with this container right now.

**Comment by aomaryoussef** [comment]
I have the same issue

**Comment by V-Shadbolt** [comment]
@aomaryoussef can you share your docker compose and your environment? Logs would also be helpful.

As before I'm unable to reproduce the issue.

**Comment by imhinotori** [comment]
This happens when you change the db type after the first initialization, to fix this, just rebuild the container with the env BUILD: true.

**Comment by mariushosting** [comment]
> @aomaryoussef can you share your docker compose and your environment? Logs would also be helpful.
> 
> As before I'm unable to reproduce the issue.

I can confirm the issue has been resolved in Version 5.6.0 Thjank you @V-Shadbolt
